spring.application.name=paymentservice
server.port=8000

spring.datasource.url=jdbc:mysql://localhost:3306/springtest
spring.datasource.username=root
spring.datasource.password=MySQLCompass
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

#RAZORPAY SECRETS
razorpay.key.RAZORPAY_KEY_ID=rzp_test_RNopBpvUbcKwIf
razorpay.key.RAZORPAY_KEY_SECRET=g6gNZbcmtT4Phq53MOtI8cbg
razorpay.key.RAZORPAY_MERCHANT_ID=NrSCBnt5hTWyf6

# KAFKA DEPENDENCY
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.consumer.group-id=payment-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
